name: Species Status Report
description: Create a species status report
title: "Species name: "
projects: ["CatalanBioGenomeProject/2"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Fill all the form to create a sequencing status report of your species
  - type: input
    id: taxid
    attributes:
      label: NCBI Taxonomic identifier
      placeholder: ex. 9606
    validations:
      required: true
  - type: input
    id: scientific_name
    attributes:
      label: Species scientific name
      placeholder: ex: Homo sapiens
    validations:
      required: true
  - type: dropdown
    id: target_list_status
    attributes:
      label: Target List status
      description: Target lists express the goals or desiderata of projects, as expressed in lists of which species they intend to generate reference sequences for
      options:
        - long_list
        - family_representative
        - other_priority
      default: 0
    validations:
      required: true
  - type: dropdown
    id: sequencing_status
    attributes:
      label: Species sequencing status
      options:
        - sample_collected
        - sample_acquired
        - data_generation
        - in_assembly

